#:kivy 1.0.9


<Car>:
    size: 32, 15
	visible: True
	
	size_hint_x: 1 if self.visible else 0
	opacity: 1 if self.visible else 0
	disabled: not self.visible
			
    canvas:
        Rectangle:
			source: 'car.png'
            pos: self.pos
            size: self.size
	canvas.before:
		PushMatrix
		Rotate:
			angle: self.angle
			origin: root.center
    canvas.after:
        PopMatrix

<CarSimulation>:
	car: car
	keep_data: True

    	
	Car:
		id: car
		center: self.parent.center
